[package]
name = "evans"
version = "0.1.1"
authors = ["Brian L. Troutwine <blt@postmates.com>"]

[[bin]]
name = "evans"
doc = false

[dependencies]
protobuf = "1.0"
clap = "2.10"
rand = "0.3"
lazy_static = "0.2"
chrono = "0.2"
byteorder = "0.5"
